services:
  postgres:
    image: docker.io/bitnami/postgresql:latest
    networks:
      - postgres
    secrets:
      - postgres
      - odoo
    deploy:
      replicas: 1
      labels:
         - traefik.enable=false
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD_FILE=/run/secrets/postgres
      - POSTGRESQL_DATABASE=odoo
      - POSTGRESQL_USERNAME=odoo
      - POSTGRESQL_PASSWORD_FILE=/run/secrets/odoo
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
    # use this for local development. Should be nfs v4 later
      - /home/raffael/Projekte/PrivateMind/postgres-odoo/data:/bitnami/postgresql
networks:
  postgres:
    driver: overlay
    attachable: true
secrets:
  postgres:
    external: true
  odoo:
    external: true